version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: auto-dep-updates
  labels:
  - ":robot: bot"
  ignore:
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
    - 12.1.0
  - dependency-name: "@commitlint/travis-cli"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
    - 12.1.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
    - 12.1.0
  - dependency-name: "@semantic-release/npm"
    versions:
    - 7.0.10
    - 7.1.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: "@semantic-release/github"
    versions:
    - 7.2.0
  - dependency-name: lodash
    versions:
    - 4.17.20
